import math
import random

PARTICLE_MASS = 1
PARTICLE_RADIUS = 5

WORLD_SIZE = 500
NUMBER_OF_PARTICLES = 200 #int(math.sqrt(WORLD_SIZE))

W = 100
#MAX_SPEED = int(W / (2 * NUMBER_OF_PARTICLES))
MAX_SPEED=0.05
TIME_STEP = 1/2*W
